### ISSUE TITLE
Изменение заголовков слайдов

### ISSUE THREAD

**Issue by ufrutov** [ConnectionAxis/ConAx#1]
В слайдах: убрать стрелочки возле заголовков **Communication**, **Collaboration**, etc.
Выделенный текст подзаголовков увеличить до размеров Semi Bold.

_Стиль подзаголовка - **h5**_
![screenshot from 2019-01-08 19-21-05](https://user-images.githubusercontent.com/5783554/50847576-9cda4980-137a-11e9-8dfd-89f71b63ea31.png)

_Стиль подзаголовка - **h4**_
![screenshot from 2019-01-08 19-23-03](https://user-images.githubusercontent.com/5783554/50847672-d90daa00-137a-11e9-82aa-3da2109bb587.png)

**Comment by ConnectionAxis** [comment]
Success!!!
